# Tests will run on push or pull request on branches main/master.

#name: Playwright Tests
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#jobs:
#  test:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#      - name: Build & Test
#        run: ./gradlew build -DincludeTags=smoke

name: Playwright Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test
        run: ./gradlew build -DincludeTags=smoke

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Deploy to GitHub Pages
        run: |
          git checkout -b gh-pages
          git rm -rf .
          cp -r allureReport/* .
          mv allureReport docs
          git add .
          git config user.name "GitHub Actions"
          git config user.email "jbogdan1998@hotmail.com"
          git commit -m "Add Allure report files"
          git push origin gh-pages
