# Tests will run on push or pull request on branches main/master.
# The workflow will install all dependencies, install Playwright and then run the tests.

name: Playwright Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
